modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mixins]]
    config = "arcadia_patch_create.mixins.json"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    displayURL = "${mod_repo_url}"
    issueTrackerURL = "${mod_issue_tracker_url}"
    description = "${mod_description}"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "create"
    type = "required"
    versionRange = "[${create_version},)"
    ordering = "AFTER"
    side = "BOTH"
